# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  my-instagram-clone:
    build:
      context: ./my-instagram-clone
    container_name: my-instagram-clone
    volumes:
      - ./my-instagram-clone:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

volumes:
  postgres_data:
