# Generated by Django 5.0.6 on 2024-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='ok'),
            preserve_default=False,
        ),
    ]
