# Generated by Django 5.0.6 on 2024-05-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_company_name_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
    ]
